name: Create GitHub Team from JSON

on:
  workflow_dispatch:  # Allows the workflow to be manually triggered

jobs:
  create-team:
    runs-on: ubuntu-latest

    steps:
      - name: Convert App token
        id: create_token
        uses: getsentry/action-github-app-token@v3.0.0
        with:
          app_id: ${{ vars.FSDH_TEAM_ADMIN_APP_ID }}
          private_key: ${{ secrets.FSDH_TEAM_ADMIN_APP_KEY }}

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        run: gh auth login --with-token <<< "${{ steps.create_token.outputs.token }}"

      - name: Find and Parse Team JSON Files
        run: |
          team_files=$(find ./.github/workflows/team-configs -name '*.json')
          echo "$team_files" | tr ' ' '\n' | while read -r team_file; do
            team=$(cat "$team_file")
            TEAM_NAME=$(echo "$team" | jq -r '.name')
            TEAM_DESCRIPTION=$(echo "$team" | jq -r '.description // ""')

            # Create team
            gh api \
              --method POST \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /orgs/${{ github.repository_owner }}/teams \
              -f "name=${TEAM_NAME}" \
              -f "description=${TEAM_DESCRIPTION}" \
              -f "privacy=closed" \
              -f "permission=push" \
              -f "notification_setting=notifications_enabled"
          done